import Head from 'next/head'
import Link from 'next/link'

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <ul>
          <li>
            <Link href="/">
              <a className='underline'>Home</a>
            </Link>
          </li>
          <li>
            <Link href="/admin">
              <a className='underline'>Admin</a>
            </Link>
          </li>
        </ul>
      </nav>
      <main>{children}</main>
      <footer>
      </footer>
    </>
  )
}