import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image"
import { useSession, signIn, signOut } from "next-auth/react"

const Nav = () => {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Video course starter kit – powered by Mux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex justify-center items-center py-4">
        <Link href="/" passHref>
          <a className="flex justify-center items-center">
            <Image
              alt="Video course starter kit"
              height={32}
              src="/images/mux-logo.png"
              width={100}
            />
            <span className="inline-block ml-3 font-medium truncate">
              Video Course Starter Kit
            </span>
          </a>
        </Link>
      </nav>
      <nav className='p-4'>
        <ul className='flex gap-2'>
          <li>
            <Link href="/">
              <a className='underline'>Home</a>
            </Link>
          </li>
          <li>
            <Link href="/admin">
              <a className='underline'>Admin</a>
            </Link>
          </li>
          <li className='flex-1 text-right'>
            {session ? (
              <>
                Signed in as {session.user?.email} <br />
                <button onClick={() => signOut()}>Sign out</button>
              </>
            ) : (
              <p>
                <button onClick={() => signIn()}>Sign in with Github</button>
              </p>
            )}
          </li>
        </ul>
      </nav>
    </>
  )
}

export default Nav;